name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: configure
      run: ./configure
    - name: cmake
      run: cmake
    - name: cmake check
      run: cmake check
    - name: cmake distcheck
      run: cmake distcheck
